config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :users

  resources :movies do
    resources :reviews, except: [:show, :index]
  end

  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :description, :movie_length,:rating,:year,:genre
  has_attached_file :image, styles: { medium: "400x600#"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates_numericality_of :rating
  validates_presence_of :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @reviews = Review.where(movie_id: @movie.id).order('created_at DESC')
  end

  # GET /movies/new
  def new
    @movie = current_user.movies.build
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = current_user.movies.build(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :movie_length, :rating, :genre, :year, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie, except: :destroy


  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit

  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.movie_id = @movie.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @movie, notice: 'Review was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-danger"   # Yellow
      when "notice"
        "alert-success"      # Blue
      else
        flash_type.to_s
    end
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'movies/navigation' %>

  <div class="container">
    <!--Alert flash message that is compatible with bootstrap -->
    <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type)%> alert-dismissible">
          <button class="close" data-dismiss="alert">×</button>
          <%= message %>
        </div>
    <% end %>

    <%= yield %>
  </div>

  </body>
</html>

app/views/movies/_form.html.erb
<div class="col-lg-6 col-md-8 col-xs-12" style="margin-bottom: 10%">

  <%= bootstrap_form_for(movie) do |f| %>
    <% if movie.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>
        <ul>
        <% movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>

      </div>
    <% end %>

      <% if movie.image_file_name.nil?  %>
          <%= f.file_field :image %>
        <% else %>
          <%= image_tag(movie.image(:medium), class: "img-fluid") %>
          <br>
          <%= f.label "Change Image" %>
          <%= f.file_field :image, hide_label: true %>
      <%end %>




      <%= f.text_field :title %>
      <%= f.text_area :description  %>
      <%= f.text_field :movie_length %>
      <%= f.text_field :rating %>
      <%= f.text_field :year %>
      <%= f.text_field :genre %>
      <%= f.submit %>
  <% end %>
</div>

app/views/movies/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Reviews", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <% if current_user.email == "admin@email.com" %>
                <li style="margin-top: 3px; margin-right: 3px"><%= link_to "Add Movie", new_movie_path, class: "btn btn-default", style: "padding: 10px" %></li>
            <% end %>

            <li style="margin-top: 3px" ><%= link_to "Sign Out", destroy_user_session_path, :method => :delete,  class: "btn btn-default", style: "padding: 10px" %></li>
        <% else %>
            <li style="margin-top: 3px"><%= link_to "Sing In", new_user_session_path, class: "btn btn-default", style: "padding: 10px" %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</nav>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/index.html.erb
<div class="row">
  <% @movies.each do |movie| %>
    <div class="col-md-3 col-sm-6">
      <div class="thumbnail">
          <%= link_to image_tag(movie.image(:medium)), movie %>
      </div>
      <p style="text-align: center"><%= movie.title %></p>
    </div>
  <%end%>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image(:medium), class: "img-fluid"%>
        <div class="table-responsive">
          <table class="table">
            <tbody>
            <tr>
              <td>Title:</td>
              <td><%= @movie.title%></td>
            </tr>

            <tr>
              <td>Description:</td>
              <td><%= @movie.description %></td>
            </tr>

            <tr>
              <td>Length:</td>
              <td><%= @movie.movie_length %></td>
            </tr>

            <tr>
              <td>Rating:</td>
              <td><%= @movie.rating %></td>
            </tr>

            <tr>
              <td>Year:</td>
              <td><%= @movie.year %></td>
            </tr>

            <tr>
              <td>Genre:</td>
              <td><%= @movie.genre %></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="col-md-7 col-md-offset-1">
        <h2><%= "#{@movie.title} Reviews" %></h2>
        <% if @reviews.blank? %>
            <h3>There are no reviews for this movie yet.</h3>
            <%= link_to "Write a Review", new_movie_review_path(@movie), class: "btn btn-default"%>
        <% else %>
            <% @reviews.each do |r| %>
                <Strong><%= r.title %></Strong>
                <div class="star-rating" data-score= <%= r.rating %> ></div>
                <p><%= r.comment %></p>
                <% unless current_user.nil? %>
                  <% if current_user.id == r.user_id  %>
                        <div style="text-align: right">
                          <%= link_to "Edit", edit_movie_review_path(@movie,r), class: "btn btn-warning" %>
                          <%= link_to "Delete", review_path(r), class: "btn btn-danger", :method => :delete, data: { confirm: 'Are you certain you want to delete this?' } %>
                        </div>
                  <% end %>
                <%end %>
                <hr>
            <% end %>
        <% end %>

      </div>

    </div>
      <%= link_to "Write a Review", new_movie_review_path(@movie), class: "btn btn-lg btn-success"%>
  </div>
</div>

<% if user_signed_in? %>
    <% if current_user.id == @movie.user_id %>
        <%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-warning" %>
    <% end %>
<% end %>
<%= link_to 'Back', movies_path, class: "btn btn-default" %>

<script>
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
  <%= bootstrap_form_for([@movie,@review]) do |f| %>
    <% if review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
        <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

      <br>

      <%= f.label :rating %>
      <% if @review.rating.nil? %>
          <div id="star-rating"></div>
      <% else %>
          <div id="star-rating" ></div>
      <% end %>
      <br>
      <%= f.text_field :title %>
      <%= f.text_area :comment %>
      <%= f.submit %>
  <% end %>

  <script>
    $('#star-rating').raty({
      path: '/assets/',
      scoreName: 'review[rating]',
    });
  </script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>
<br>
<%= link_to "Back", movie_path(@movie), class: "btn btn-default" %>

app/views/reviews/new.html.erb
<div class="col-md-6">
<h1>New Review</h1>

<%= render 'form', review: @review %>
<br>
<%= link_to "Back", movie_path(@movie), class: "btn btn-default" %>
</div>